import type { WorkshopState } from "@/types/motoflow";

const now = new Date().toISOString();
const tallerId = "11111111-1111-4111-8111-111111111111";

export const mockData: WorkshopState = {
  clientes: [
    {
      id: "cliente-ana",
      taller_id: tallerId,
      nombre: "Ana Martinez",
      telefono: "333 410 2210",
      localidad: "Ciudad Guzman",
      notas: "Prefiere recibir actualizaciones por llamada.",
      created_at: now,
      updated_at: now,
    },
    {
      id: "cliente-carlos",
      taller_id: tallerId,
      nombre: "Carlos Rivera",
      telefono: "333 880 9090",
      localidad: "Zapotiltic",
      notas: "Cliente frecuente.",
      created_at: now,
      updated_at: now,
    },
  ],
  motocicletas: [
    {
      id: "moto-ninja",
      taller_id: tallerId,
      cliente_id: "cliente-ana",
      marca: "Kawasaki",
      modelo: "Ninja 400",
      anio: 2022,
      placas: "7MOT21",
      color: "Verde",
      kilometraje: 12800,
      numero_serie: "KAW4002022MX",
      notas: "Servicio mayor cada 6000 km.",
      created_at: now,
      updated_at: now,
    },
    {
      id: "moto-italika",
      taller_id: tallerId,
      cliente_id: "cliente-carlos",
      marca: "Italika",
      modelo: "FT150",
      anio: 2020,
      placas: "4TAL20",
      color: "Rojo",
      kilometraje: 34200,
      notas: "Uso diario para reparto.",
      created_at: now,
      updated_at: now,
    },
  ],
  ordenes: [
    {
      id: "orden-001",
      taller_id: tallerId,
      cliente_id: "cliente-ana",
      moto_id: "moto-ninja",
      titulo: "Revision de frenos delanteros",
      descripcion_problema: "Vibracion al frenar y sonido metalico.",
      diagnostico: "Discos con desgaste irregular. Requiere balatas nuevas.",
      prioridad: "alta",
      estado: "esperando_autorizacion",
      fecha_entrada: "2026-06-29",
      fecha_estimada: "2026-07-02",
      total_estimado: 2800,
      notas_internas: "Confirmar disponibilidad de balatas OEM.",
      notas_publicas: "Diagnostico listo. Esperamos autorizacion para continuar.",
      codigo_publico: "MF-NINJA1",
      created_at: now,
      updated_at: now,
    },
    {
      id: "orden-002",
      taller_id: tallerId,
      cliente_id: "cliente-carlos",
      moto_id: "moto-italika",
      titulo: "Servicio preventivo",
      descripcion_problema: "Cambio de aceite, bujia y revision general.",
      diagnostico: "Servicio en proceso.",
      prioridad: "media",
      estado: "en_reparacion",
      fecha_entrada: "2026-06-30",
      fecha_estimada: "2026-07-01",
      total_estimado: 950,
      notas_publicas: "La motocicleta esta en reparacion.",
      codigo_publico: "MF-FT150",
      created_at: now,
      updated_at: now,
    },
  ],
  evidencias: [],
  movimientos: [],
  cotizaciones: [],
};
